version: '1.0'
services:
  taskforce.postgres:
    image: postgres:14-alpine
    container_name: taskforce.postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test
      POSTGRES_DB: taskforce
    ports:
      - 5432:5432
    volumes:
      - taskforce.postgres:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d test" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - taskforce

  taskforce.pgadmin:
    image: dpage/pgadmin4
    container_name: taskforce.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "unknown@mail.local"
      PGADMIN_DEFAULT_PASSWORD: "test"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - 8082:80
    networks:
      - taskforce

volumes:
  taskforce.postgres:

networks:
  taskforce:
      driver: bridge
