version: '3.8'
services:
  taskforce.postgres:
    image: postgres:14-alpine
    container_name: taskforce.postgres
    environment:
      POSTGRES_USER: ${POSTGRES_ROOT_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
      - ${POSTGRES_DB_PORT}:5432
    volumes:
      - taskforce.postgres:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d pass" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - taskforce

  taskforce.pgadmin:
    image: dpage/pgadmin4
    container_name: taskforce.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "unknown@mail.local"
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - ${PGADMIN_DB_PORT}:80
    networks:
      - taskforce

volumes:
  taskforce.postgres:

networks:
  taskforce:
      driver: bridge
