version: "1.0"
services:
  mongo_db:
    build: ./mongodb-replica
    restart: always
    container_name: taskforce.mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27017
    ports:
      - 27017:27017
    volumes:
      - taskforce_data:/data/db

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/taskforce --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  mongo_ui:
    image: mongo-express:latest
    restart: always
    container_name: taskforce.mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://admin:pass@mongo_db:27017/

volumes:
  taskforce_data:
