version: "1.0"
services:
  db:
    image: mongo:4.2
    restart: always
    container_name: taskforce.mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
      MONGO_INITDB_DATABASE: taskforce-users-feedbacks
    ports:
      - 27017:27017
    volumes:
      - taskforce_data:/data/db

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/taskforce-users-feedbacks --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  db_ui:
    image: mongo-express:latest
    restart: always
    container_name: taskforce.mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_DB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_DB_USER}:${MONGO_DB_PASSWORD}@db:${MONGO_DB_PORT}/

volumes:
  taskforce_data:
